name: ci

on:
  push:
    branches:
      - "main"
      - "master"
env:
  REGISTRY_IMAGE: gitea.slowb.ro/slowb.ro/0x1a

jobs:
  build:
    runs-on: ubuntu-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Gitea Registry
        uses: docker/login-action@v2
        with:
          registry: gitea.slowb.ro
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        env:
          ACTIONS_RUNTIME_TOKEN: ''
        with:
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest
          platforms: linux/amd64, linux/arm64