"""Add is_confirmed and confirmed_on fields

Revision ID: 30c31cc400fd
Revises: 80fc049de1ce
Create Date: 2024-03-30 23:16:18.588676

"""

# revision identifiers, used by Alembic.
revision = '30c31cc400fd'
down_revision = '80fc049de1ce'

from alembic import op
import sqlalchemy as sa
from fhost import app, User  # Import your User model


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(), nullable=True))
        batch_op.drop_column('email_verified_at')

    # ### end Alembic commands ###
    update_default_user_confirmed()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('is_confirmed')


def update_default_user_confirmed():
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    try:
        # Update User records where is_confirmed is NULL
        session.query(User).filter(User.is_confirmed == None).update({"is_confirmed": False})
        session.commit()
    except Exception as e:
        session.rollback()
        raise e
    finally:
        session.close()
