"""create user table

Revision ID: 80fc049de1ce
Revises: dd0766afb7d2
Create Date: 2024-03-20 02:13:10.416056

"""

# revision identifiers, used by Alembic.
revision = '80fc049de1ce'
down_revision = 'dd0766afb7d2'

from alembic import op
import sqlalchemy as sa
from hashlib import sha256
from fhost import app, User  # Import your User model
from werkzeug.security import generate_password_hash


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.UnicodeText(length=255), nullable=False),
    sa.Column('fullname', sa.UnicodeText(length=255), nullable=True),
    sa.Column('biography', sa.UnicodeText(length=10000), nullable=True),
    sa.Column('email', sa.UnicodeText(length=255), nullable=False),
    sa.Column('password', sa.UnicodeText(length=255), nullable=False),
    sa.Column('website', sa.UnicodeText(length=1000), nullable=True),
    sa.Column('location', sa.UnicodeText(length=255), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('hide_email', sa.Boolean(), nullable=True),
    sa.Column('hide_activity', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('avatar_method', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.UnicodeText(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('remember_token', sa.UnicodeText(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('visibility IN (1, 2, 3)', name='valid_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    insert_initial_values()
    # ### end Alembic commands ###
    
def insert_initial_values():
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    user1 = User(username='anonymous', email='anonymous@zxz.com', password=generate_password_hash(""))
    user1.activate_user()
    session.add(user1)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
