"""Create user table

Revision ID: e97ef20acc5a
Revises: dd0766afb7d2
Create Date: 2024-03-11 17:10:02.842323

"""

# revision identifiers, used by Alembic.
revision = 'e97ef20acc5a'
down_revision = 'dd0766afb7d2'

from alembic import op
import sqlalchemy as sa
from hashlib import sha256
from fhost import app, User  # Import your User model
from werkzeug.security import generate_password_hash

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.UnicodeText(length=255), nullable=False),
    sa.Column('email', sa.UnicodeText(length=255), nullable=False),
    sa.Column('password', sa.UnicodeText(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('remember_token', sa.UnicodeText(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    insert_initial_values()
    # ### end Alembic commands ###

def insert_initial_values():
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    user1 = User(username='anonymous', email='anonymous@zxz.com', password=generate_password_hash(""))
    user1.activate_user()
    session.add(user1)
    session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
